var itemsTemplate = [
  {
    type: "",
    brand: "",
    name: "",
    link: "",
    hot: false,
    sale: false,
    image: "",
    feature: ["", "", "", ""],
  },
];
var itemsTD = [
  {
    type: "Tube Dryer",
    brand: "Isotech",
    name: "TD-03",
    link: "?page=td03",
    hot: false,
    sale: true,
    image: "./assets/images/products/td03.png",
    feature: [
      "เป็นเครื่องสำหรับอบแห้ง สายยาง สายเครื่องช่วยหายใจ ขนาด 600 ลิตร สามารถอบแห้งสายตั้งแต่ขนาดเล็กจนถึงสายสำหรับ เครื่องช่วยหายใจ เครื่องดมยาสลบ อุปกรณ์เครื่องช่วยหายใจและอุปกรณ์อื่นๆ ได้พร้อมกันถึง 80 เส้น โดยใช้ความร้อน",
      "สามารถปรับอุณหภูมิได้ตั้งแต่เหนืออุณหภูมิห้อง 5 °C ถึง 80 °C พร้อมระบบควบคุมอุณหภูมิให้คงที่ ด้วย ไมโครโปรเซสเซอร์",
      "สามารถใช้งานได้ทั้งแบบกำหนดเวลา (Automatic) แบบต่อเนื่อง (Manual)",
      "เป็นผลิตภัณฑ์ ISOTECH ประเทศไทย รับประกัน 1 ปี",
    ],
  },
  {
    type: "Tube Dryer",
    brand: "Isotech",
    name: "TD-04",
    link: "?page=td04",
    hot: false,
    sale: true,
    image: "./assets/images/products/td04.png",
    feature: [
      "เป็นเครื่องสำหรับอบแห้ง สายยาง สายเครื่องช่วยหายใจ ขนาด 450 ลิตร สามารถอบแห้งสายตั้งแต่ขนาดเล็กจนถึงสายสำหรับ เครื่องช่วยหายใจ เครื่องดมยาสลบ อุปกรณ์เครื่องช่วยหายใจและอุปกรณ์อื่นๆ ได้พร้อมกันถึง 84 เส้น โดยใช้ความร้อน",
      "สามารถปรับอุณหภูมิได้ตั้งแต่เหนืออุณหภูมิห้อง 5 °C ถึง 80 °C พร้อมระบบควบคุมอุณหภูมิให้คงที่ ด้วย ไมโครโปรเซสเซอร์",
      "สามารถใช้งานได้ทั้งแบบกำหนดเวลา (Automatic) แบบต่อเนื่อง (Manual)",
      "เป็นผลิตภัณฑ์ ISOTECH ประเทศไทย รับประกัน 1 ปี",
    ],
  },
  {
    type: "Tube Dryer",
    brand: "Isotech",
    name: "TD-05",
    link: "?page=td05",
    hot: false,
    sale: true,
    image: "./assets/images/products/td05.jpg",
    feature: [
      "เป็นเครื่องสำหรับอบแห้ง สายยาง สายเครื่องช่วยหายใจ ขนาด 1200 ลิตร สามารถอบแห้งสายตั้งแต่ขนาดเล็กจนถึงสายสำหรับ เครื่องช่วยหายใจ เครื่องดมยาสลบ อุปกรณ์เครื่องช่วยหายใจและอุปกรณ์อื่นๆ ได้พร้อมกันถึง 200 เส้น โดยใช้ความร้อน",
      "สามารถปรับอุณหภูมิได้ตั้งแต่เหนืออุณหภูมิห้อง 5 °C ถึง 80 °C พร้อมระบบควบคุมอุณหภูมิให้คงที่ ด้วย ไมโครโปรเซสเซอร์",
      "สามารถใช้งานได้ทั้งแบบกำหนดเวลา (Automatic) แบบต่อเนื่อง (Manual)",
      "เป็นผลิตภัณฑ์ ISOTECH ประเทศไทย รับประกัน 1 ปี",
    ],
  },
  {
    type: "Warmer Solution Cabinet",
    brand: "Isotech",
    name: "WS-01",
    link: "?page=ws01",
    hot: true,
    sale: true,
    image: "./assets/images/products/ws-01.jpg",
    feature: [
      "เป็นเครื่องสำหรับอุ่นสารละลาย ได้ครั้งละไม่น้อยกว่า 70 ขวด โดยใช้ความร้อน",
      "สามารถปรับอุณหภูมิได้ตั้งแต่เหนืออุณหภูมิห้อง 5 °C ถึง 60 °C พร้อมระบบควบคุมอุณหภูมิให้คงที่ด้วยไมโครโปรเซสเซอร์",
      "สามารถใช้งานได้ทั้งแบบกำหนดเวลา (Automatic) แบบต่อเนื่อง (Manual)",
      "เป็นผลิตภัณฑ์ ISOTECH ประเทศไทย รับประกัน 1 ปี",
    ],
  },
  {
    type: "Warmer Solution Cabinet",
    brand: "Isotech",
    name: "WS-02",
    link: "?page=ws02",
    hot: true,
    sale: true,
    image: "./assets/images/products/ws-02.jpg",
    feature: [
      "เป็นเครื่องสำหรับอุ่นสารละลาย ได้ครั้งละไม่น้อยกว่า 30 ขวด โดยใช้ความร้อน",
      "สามารถปรับอุณหภูมิได้ตั้งแต่เหนืออุณหภูมิห้อง 5 °C ถึง 60 °C พร้อมระบบควบคุมอุณหภูมิให้คงที่ด้วยไมโครโปรเซสเซอร์",
      "สามารถใช้งานได้ทั้งแบบกำหนดเวลา (Automatic) แบบต่อเนื่อง (Manual)",
      "เป็นผลิตภัณฑ์ ISOTECH ประเทศไทย รับประกัน 1 ปี",
    ],
  },
  {
    type: "Warmer Solution Cabinet",
    brand: "Isotech",
    name: "WSC",
    link: "?page=wsc",
    hot: true,
    sale: true,
    image: "./assets/images/products/wsc.jpg",
    feature: [
      "เป็นเครื่องสำหรับอุ่นสารละลายโดยใช้ความร้อน",
      "สามารถปรับอุณหภูมิได้ตั้งแต่เหนืออุณหภูมิห้อง 5 °C ถึง 60 °C พร้อมระบบควบคุมอุณหภูมิให้คงที่ด้วยไมโครโปรเซสเซอร์",
      "สามารถใช้งานได้ทั้งแบบกำหนดเวลา เปิด-ปิด อัตโนมัติ (Automatic) แบบต่อเนื่อง (Manual)",
      "มีไฟแสดงสถานะการทำงานของฮีทเตอร์",
      "เป็นผลิตภัณฑ์ ISOTECH ประเทศไทย รับประกัน 1 ปี",
    ],
  },
];
var itemsVapor = [
  {
    type: "Vaporizer Analyzer",
    brand: "BC Biomedical",
    name: "AA-8000",
    link: "?page=aa8000",
    hot: true,
    sale: false,
    image: "./assets/images/products/aa8000.png",
    feature: [
      "ตรวจวัดสารสลบได้ 4 ชนิด: Sevoflurane, Isoflurane, Desflurane and Halothan",
      "มีปั๊มในตัว",
      "บันทึกค่าแบบ Data Logging",
      "ผลิตในสหรัฐอเมริกา",
    ],
  },
  {
    type: "Vaporizer Analyzer",
    brand: "BC Biomedical",
    name: "AA-8100",
    link: "?page=aa8100",
    hot: false,
    sale: false,
    image: "./assets/images/products/aa8100.png",
    feature: [
      "ตรวจวัดสารสลบ อัตโนมัติ",
      "ตรวจวัดสารสลบได้ 4 ชนิด: Sevoflurane, Isoflurane, Desflurane and Halothan",
      "สามารถวัด CO2 ได้",
      "สามารถใช้ Bluetooth ร่วมกับ Appliction myBC",
      "มีปั๊มในตัว",
      "บันทึกค่าแบบ Data Logging",
      "ผลิตในสหรัฐอเมริกา",
    ],
  },
  {
    type: "Vaporizer Analyzer",
    brand: "Riken Keiki",
    name: "FI-8000P",
    link: "?page=fi8000p",
    hot: false,
    sale: false,
    image: "./assets/images/products/fi8000p.jpg",
    feature: [
      "ตรวจวัดสารสลบได้ 4 ชนิด: Sevoflurane, Isoflurane, Desflurane and Halothan",
      "มีปั๊มในตัว",
      "ใช้แบตเตอรี่ AA",
    ],
  },
];
var itemsVen = [
  {
    type: "Ventilator Analyzer",
    brand: "TSI",
    name: "Certifier FA Plus 4080",
    link: "?page=faplus4080",
    hot: false,
    sale: false,
    image: "./assets/images/products/faplus4080.jpg",
    feature: [
      "หน้าจอสีแบบสัมผัส",
      "แสดงกราฟแบบ Real-Time",
      "วัดการไหลได้ทั้งไปและกลับ",
      "หน่วยความจำในตัว",
      "พิมพ์ Report ได้",
    ],
  },
  {
    type: "Ventilator Analyzer",
    brand: "TSI",
    name: "Certifier FA 4070",
    link: "?page=fa4070",
    hot: false,
    sale: false,
    image: "./assets/images/products/fa4070.png",
    feature: [
      "หน้าจอแบบสัมผัส",
      "แสดงกราฟแบบ Real-Time",
      "วัดการไหลได้ทั้งไปและกลับ",
      "หน่วยความจำในตัว",
      "พิมพ์ Report ได้",
    ],
  },
  {
    type: "Ventilator Analyzer",
    brand: "BC Biomedical",
    name: "PFC-3000 Series",
    link: "?page=pfc3000",
    hot: false,
    sale: false,
    image: "./assets/images/products/pfc3000.jpg",
    feature: [
      "16 respiratory parameters",
      "Two measuring ports evaluate flow, pressure,temperature, humidity and O2",
      "13 gas standards and 10 gas types ",
      "Internally stores all measured and respiratory parameters",
    ],
  },
  {
    type: "Ventilator Analyzer",
    brand: "IMT Analytics",
    name: "Citrex H4",
    link: "?page=citrex-h4",
    hot: true,
    sale: false,
    image: "./assets/images/products/h4.jpg",
    feature: [
      "หน้าจอแบบสัมผัส",
      "แสดงกราฟแบบ Real-Time",
      "วัดการไหลได้ทั้งไปและกลับ",
      "บันทึกผลลง micro SD Card",
      "น้ำหนักเบาพกพาสะดวก",
    ],
  },
  {
    type: "Ventilator Analyzer",
    brand: "IMT Analytics",
    name: "Citrex H5",
    link: "?page=citrex-h5",
    hot: false,
    sale: false,
    image: "./assets/images/products/h5.jpg",
    feature: [
      "หน้าจอแบบสัมผัส 4.3 นิ้ว",
      "แสดงกราฟแบบ Real-Time",
      "Extended profile capabilities",
      "Flow and pressure trigger settings",
      "Up to 17 gas standards and up to 26 respiratory parameters",
      "วัดการไหลได้ทั้งไปและกลับ",
      "บันทึกผลลง micro SD Card",
      "การประเมิณสถิติ",
      "น้ำหนักเบาพกพาสะดวก",
    ],
  },
];
var itemsDefib = [
  {
    type: "Defib/Pacer Analyzer",
    brand: "BC Biomedical",
    name: "DA-2006",
    link: "?page=da-2006",
    hot: false,
    sale: false,
    image: "./assets/images/products/da2006.jpg",
    feature: [
      "มีการแสดงผลหน้าจอ Backlight แบบหลายพารามิเตอร์",
      "แสดงผล Waveform ของ Defibrillator และ Pacemaker บนหน้าจอ",
      "สามารถทดสอบทั้งแบบ Monophasic และ Biphasic",
      "รองรับการทดสอบสูงสุด 5000 โวลต์, 1000 จูลล์",
      "สามารถวัด Cardioversion delay",
      "สามารถวัด Charge time",
      "บันทึก Waveform ได้",
      "การเชื่อมต่อ ECG แบบ 12 lead",
      "สามารถจำลองสัญญาณ ECG แบบปกติ และผิดปกติได้",
      "เชื่อมต่อ Printer ด้วยพาราเรลพอร์ท",
      "ทำงานด้วยแบตเตอรี่ 9V และมีไฟแสดงสถานะเมื่อแบตเตอรี่ต่ำ",
      "สามารถทดสอบแบบ Auto sequence",
    ],
  },
  {
    type: "Defib/Pacer Analyzer",
    brand: "BC Biomedical",
    name: "DA-2006P",
    link: "?page=da-2006p",
    hot: false,
    sale: false,
    image: "./assets/images/products/da2006p.jpg",
    feature: [
      "มีการแสดงผลหน้าจอ Backlight แบบหลายพารามิเตอร์",
      "แสดงผล Waveform ของ Defibrillator และ Pacemaker บนหน้าจอ",
      "สามารถทดสอบทั้งแบบ Monophasic และ Biphasic",
      "รองรับการทดสอบสูงสุด 5000 โวลต์, 1000 จูลล์",
      "สามารถวัด Cardioversion delay",
      "สามารถวัด Charge time",
      "บันทึก Waveform ได้",
      "การเชื่อมต่อ ECG แบบ 12 lead",
      "สามารถจำลองสัญญาณ ECG แบบปกติ และผิดปกติได้",
      "เชื่อมต่อ Printer ด้วยพาราเรลพอร์ท",
      "ทำงานด้วยแบตเตอรี่ 9V และมีไฟแสดงสถานะเมื่อแบตเตอรี่ต่ำ",
      "สามารถทดสอบแบบ Auto sequence",
      "เลือก Load สำหรับการทดสอบได้ 26 ค่า (เฉพาะรุ่น DA-2006P)",
      "Full Pulse Analysis (เฉพาะรุ่น DA-2006P)",
      "สามารถทดสอบ Demand Sensitive (เฉพาะรุ่น DA-2006P)",
      "สามารถทดสอบ Refractory Period (เฉพาะรุ่น DA-2006P)",
      "สามารถจำลองสัญญาณรบกวน 50/60 Hz (เฉพาะรุ่น DA-2006P)",
      "การปกป้อง Pacer Input (เฉพาะรุ่น DA-2006P)",
    ],
  },
  {
    type: "Defib/Pacer Analyzer",
    brand: "S.P.L. Elektronik",
    name: "DP-600",
    link: "?page=dp600",
    hot: false,
    sale: false,
    image: "./assets/images/products/dp600.jpg",
    feature: [
      "เครื่องกระตุ้นหัวใจแบบ single-, dual- และ triple-circuit",
      "การวัดค่า defi-impulses ขั้วอิสระ",
      "แสดงผล Discharge เป็นแบบกราฟฟิค",
      "หน้าจอทัชสกรีนหรือควบคุมด้วยคอมพิวเตอร์",
      "การจำลองสัญญาณ ECG",
      "นาฬิกาจับเวลาสำหรับการ Charge และ Discharge",
    ],
  },
];
var itemsESA = [
  {
    type: "Electrical Safety Analyzer",
    brand: "BC Biomedical",
    name: "SA-2000",
    link: "?page=sa2000",
    hot: false,
    sale: false,
    image: "./assets/images/products/sa2000.jpg",
    feature: [
      "ตัวเครื่องมีขนาดที่เล็ก พกพาสะดวก",
      "สามารถวัดแรงดันและกระแสไฟฟ้าแบบ True RMS",
      "สามารถการวัดความต้านทานสายดินและกระแสรั่วไหล Earth Leakage Current",
      "สามารถทำการวัดแบบ Point-to-Point (บางรุ่น)",
      "สามารถวัดกระแสรั่วไหลจากตัวถัง",
      "สามารถวัดความต้านและกระแสรั่วไหลภายนอก",
      "ตรวจสอบความสมบูรณ์ของแหล่งจ่ายไฟ",
      "MAP (Isolation) Function",
      "สามารถจำลองสัญญาณ ECG ได้ (บางรุ่น)",
      "การเลือก Load สำหรับมาตรฐาน AAMI ES1-1993 หรือ IEC 601 (เฉพาะรุ่น 2001 ขึ้นไป)",
      "ใช้งานกับแรงดัน 85 to 265 VAC",
      "รองรับกระแสสูงสุด 20 แอมป์",
      "ควบคุมด้วยปุ่มสัมผัส",
      "มีไฟแสดงสถานะ LED",
      "การตอบสนองด้วยเสียง",
      "มีจุดทำหรับ Self-Test (บางรุ่น)",
      "จุดเปลี่ยน Fuse ภายนอกเครื่อง",
      "Automatic Load Reversal Delay",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "BC Biomedical",
    name: "SA-2001",
    link: "?page=sa2001",
    hot: false,
    sale: false,
    image: "./assets/images/products/sa2001.jpg",
    feature: [
      "ตัวเครื่องมีขนาดที่เล็ก พกพาสะดวก",
      "สามารถวัดแรงดันและกระแสไฟฟ้าแบบ True RMS",
      "สามารถการวัดความต้านทานสายดินและกระแสรั่วไหล Earth Leakage Current",
      "สามารถทำการวัดแบบ Point-to-Point (บางรุ่น)",
      "สามารถวัดกระแสรั่วไหลจากตัวถัง",
      "สามารถวัดความต้านและกระแสรั่วไหลภายนอก",
      "ตรวจสอบความสมบูรณ์ของแหล่งจ่ายไฟ",
      "MAP (Isolation) Function",
      "สามารถจำลองสัญญาณ ECG ได้ (บางรุ่น)",
      "การเลือก Load สำหรับมาตรฐาน AAMI ES1-1993 หรือ IEC 601 (เฉพาะรุ่น 2001 ขึ้นไป)",
      "ใช้งานกับแรงดัน 85 to 265 VAC",
      "รองรับกระแสสูงสุด 20 แอมป์",
      "ควบคุมด้วยปุ่มสัมผัส",
      "มีไฟแสดงสถานะ LED",
      "การตอบสนองด้วยเสียง",
      "มีจุดทำหรับ Self-Test (บางรุ่น)",
      "จุดเปลี่ยน Fuse ภายนอกเครื่อง",
      "Automatic Load Reversal Delay",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "BC Biomedical",
    name: "SA-2005",
    link: "?page=sa2005",
    hot: false,
    sale: false,
    image: "./assets/images/products/sa2005.jpg",
    feature: [
      "ตัวเครื่องมีขนาดที่เล็ก พกพาสะดวก",
      "สามารถวัดแรงดันและกระแสไฟฟ้าแบบ True RMS",
      "สามารถการวัดความต้านทานสายดินและกระแสรั่วไหล Earth Leakage Current",
      "สามารถทำการวัดแบบ Point-to-Point (บางรุ่น)",
      "สามารถวัดกระแสรั่วไหลจากตัวถัง",
      "สามารถวัดความต้านและกระแสรั่วไหลภายนอก",
      "ตรวจสอบความสมบูรณ์ของแหล่งจ่ายไฟ",
      "MAP (Isolation) Function",
      "สามารถจำลองสัญญาณ ECG ได้ (บางรุ่น)",
      "การเลือก Load สำหรับมาตรฐาน AAMI ES1-1993 หรือ IEC 601 (เฉพาะรุ่น 2001 ขึ้นไป)",
      "ใช้งานกับแรงดัน 85 to 265 VAC",
      "รองรับกระแสสูงสุด 20 แอมป์",
      "ควบคุมด้วยปุ่มสัมผัส",
      "มีไฟแสดงสถานะ LED",
      "การตอบสนองด้วยเสียง",
      "มีจุดทำหรับ Self-Test (บางรุ่น)",
      "จุดเปลี่ยน Fuse ภายนอกเครื่อง",
      "Automatic Load Reversal Delay",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "BC Biomedical",
    name: "SA-2010",
    link: "?page=sa2010",
    hot: false,
    sale: false,
    image: "./assets/images/products/sa2010.jpg",
    feature: [
      "ตัวเครื่องมีขนาดที่เล็ก พกพาสะดวก",
      "สามารถวัดแรงดันและกระแสไฟฟ้าแบบ True RMS",
      "สามารถการวัดความต้านทานสายดินและกระแสรั่วไหล Earth Leakage Current",
      "สามารถทำการวัดแบบ Point-to-Point (บางรุ่น)",
      "สามารถวัดกระแสรั่วไหลจากตัวถัง",
      "สามารถวัดความต้านและกระแสรั่วไหลภายนอก",
      "ตรวจสอบความสมบูรณ์ของแหล่งจ่ายไฟ",
      "MAP (Isolation) Function",
      "สามารถจำลองสัญญาณ ECG ได้ (บางรุ่น)",
      "การเลือก Load สำหรับมาตรฐาน AAMI ES1-1993 หรือ IEC 601 (เฉพาะรุ่น 2001 ขึ้นไป)",
      "ใช้งานกับแรงดัน 85 to 265 VAC",
      "รองรับกระแสสูงสุด 20 แอมป์",
      "ควบคุมด้วยปุ่มสัมผัส",
      "มีไฟแสดงสถานะ LED",
      "การตอบสนองด้วยเสียง",
      "มีจุดทำหรับ Self-Test (บางรุ่น)",
      "จุดเปลี่ยน Fuse ภายนอกเครื่อง",
      "Automatic Load Reversal Delay",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "BC Biomedical",
    name: "SA-2010S",
    link: "?page=sa2010s",
    hot: true,
    sale: false,
    image: "./assets/images/products/sa2010s.jpg",
    feature: [
      "ตัวเครื่องมีขนาดที่เล็ก พกพาสะดวก",
      "สามารถวัดแรงดันและกระแสไฟฟ้าแบบ True RMS",
      "สามารถการวัดความต้านทานสายดินและกระแสรั่วไหล Earth Leakage Current",
      "สามารถทำการวัดแบบ Point-to-Point (บางรุ่น)",
      "สามารถวัดกระแสรั่วไหลจากตัวถัง",
      "สามารถวัดความต้านและกระแสรั่วไหลภายนอก",
      "ตรวจสอบความสมบูรณ์ของแหล่งจ่ายไฟ",
      "MAP (Isolation) Function",
      "สามารถจำลองสัญญาณ ECG ได้ (บางรุ่น)",
      "การเลือก Load สำหรับมาตรฐาน AAMI ES1-1993 หรือ IEC 601 (เฉพาะรุ่น 2001 ขึ้นไป)",
      "ใช้งานกับแรงดัน 85 to 265 VAC",
      "รองรับกระแสสูงสุด 20 แอมป์",
      "ควบคุมด้วยปุ่มสัมผัส",
      "มีไฟแสดงสถานะ LED",
      "การตอบสนองด้วยเสียง",
      "มีจุดทำหรับ Self-Test (บางรุ่น)",
      "จุดเปลี่ยน Fuse ภายนอกเครื่อง",
      "Automatic Load Reversal Delay",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "S.P.L. Elektronik",
    name: "GM-610",
    link: "?page=gm610",
    hot: false,
    sale: false,
    image: "./assets/images/products/gm610.png",
    feature: [
      "ระบบทดสอบทดสอบความปลอดภัยทางไฟฟ้าตาม IEC 60601 / IEC 62353 / IEC 61010 / VDE 0701-0702 MPG / MPBetreibV / BetrSichV / DGUV Vorschrift 3",
      "หน้าจอระบบสัมผัส หรือควบคุมด้วยคอมพิวเตอร์",
      "มีช่องเชื่อมต่อคีย์บอร์ดและบาร์โค้ด",
      "หน่วยความจำภายในสำหรับคำสั่งและโปรโตคอลทดสอบ 200 รายการ",
      "25A PE Test ตามมาตรฐาน IEC 60601",
      "ตัวเครื่องเป็นโลหะน้ำหนักเบาทนทาน",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "S.P.L. Elektronik",
    name: "GM-410",
    link: "?page=gm410",
    hot: false,
    sale: false,
    image: "./assets/images/products/gm410.jpg",
    feature: [
      "การใช้งานร่วมกับคอมพิวเตอร์",
      "การวัดแบบอัตโนมัติหรือมัลติมิเตอร์",
      "25A PE Test ตามมาตรฐาน IEC 60601",
      "ตัวเครื่องเป็นโลหะน้ำหนักเบาทนทาน",
    ],
  },
  {
    type: "Electrical Safety Analyzer",
    brand: "S.P.L. Elektronik",
    name: "GM-300",
    link: "?page=gm300",
    hot: false,
    sale: false,
    image: "./assets/images/products/gm300.jpg",
    feature: [
      "การควบคุมด้วยเคอเซอร์ หรือควบคุมด้วยคอมพิวเตอร์",
      "มีช่องเชื่อมต่อคีย์บอร์ดและบาร์โค้ด",
      "หน่วยความจำภายในสำหรับการวัด 125 รายการหรือข้อมูลอุปกรณ์",
      "การวัดแบบอัตโนมัติหรือมัลติมิเตอร์",
      "25A PE Test ตามมาตรฐาน IEC 60601",
    ],
  },
];
var itemsNIBP = [
  {
    type: "NIBP Simulator",
    brand: "BC Biomedical",
    name: "NIBP-1010",
    link: "?page=nibp1010",
    hot: false,
    sale: false,
    image: "./assets/images/products/nibp1010.jpg",
    feature: [
      "หน้าจอแสดงผลขนาดใหญ่ แสดงผลหลายพารามิเตอร์",
      "สามารถใช้งานเป็น Manometer วัดแรงดันที่ ± 500 mmHg",
      "สามารถจำลองสัญญาณ NIBP ในโหมด Adult, Neonatal, Hypertensive และ Hypotensive",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "สามารถกำหนดค่า Envelope Shift ได้ทั้ง Systolic และ Diastolic",
      "สามารถแสดงค่า Peak Pressure ได้",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
    ],
  },
  {
    type: "NIBP Simulator",
    brand: "BC Biomedical",
    name: "NIBP-1020",
    link: "?page=nibp1020",
    hot: false,
    sale: false,
    image: "./assets/images/products/nibp1020.jpg",
    feature: [
      "หน้าจอแสดงผลขนาดใหญ่ แสดงผลหลายพารามิเตอร์",
      "สามารถใช้งานเป็น Manometer วัดแรงดันที่ ± 500 mmHg",
      "สามารถจำลองสัญญาณ NIBP ในโหมด Adult, Neonatal, Hypertensive และ Hypotensive",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "สามารถกำหนดค่า Envelope Shift ได้ทั้ง Systolic และ Diastolic",
      "สามารถแสดงค่า Peak Pressure ได้",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
      "สามารถจำลองสัญญาณ ECG ปกติ และ Performance",
      "สามารถจำลองสัญญาณ Pace Waveform",
      "สามารถจำลองอัตราการหายใจ",
    ],
  },
  {
    type: "NIBP Simulator",
    brand: "BC Biomedical",
    name: "NIBP-1030",
    link: "?page=nibp1030",
    hot: false,
    sale: false,
    image: "./assets/images/products/nibp1030.jpg",
    feature: [
      "หน้าจอแสดงผลขนาดใหญ่ แสดงผลหลายพารามิเตอร์",
      "สามารถใช้งานเป็น Manometer วัดแรงดันที่ ± 500 mmHg",
      "สามารถจำลองสัญญาณ NIBP ในโหมด Adult, Neonatal, Hypertensive และ Hypotensive",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "สามารถกำหนดค่า Envelope Shift ได้ทั้ง Systolic และ Diastolic",
      "สามารถแสดงค่า Peak Pressure ได้",
      "สามารถทดสอบการรั่วไหล (Leak rate test) ได้",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
      "สามารถจำลองสัญญาณ ECG ปกติ และ ผิดปกติได้ (ECG arrhythmia)",
      "มี ECG arrhythmia sequence สำหรับทดสอบ Alarm",
      "สามารถจำลองสัญญาณ Pace Waveform",
      "สามารถกำหนดค่าการจำลองสัญญาณ IBP ได้",
      "สามารถจำลองอัตราการหายใจ",
      "สามารถจำลองอุณหภูมิที่ใช้กับ YSI 400 และ 700",
    ],
  },
  {
    type: "NIBP Simulator",
    brand: "BC Biomedical",
    name: "NIBP-1040",
    link: "?page=nibp1040",
    hot: true,
    sale: false,
    image: "./assets/images/products/nibp1040.jpg",
    feature: [
      "หน้าจอแสดงผลขนาดใหญ่ แสดงผลหลายพารามิเตอร์",
      "สามารถใช้งานเป็น Manometer วัดแรงดันที่ ± 500 mmHg",
      "สามารถจำลองสัญญาณ NIBP ในโหมด Adult, Neonatal, Hypertensive และ Hypotensive",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "สามารถกำหนดค่า Envelope Shift ได้ทั้ง Systolic และ Diastolic",
      "สามารถแสดงค่า Peak Pressure ได้",
      "สามารถทดสอบการรั่วไหล (Leak rate test) ได้",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
      "สามารถจำลองสัญญาณ ECG ปกติ และ ผิดปกติได้ (ECG arrhythmia)",
      "มี ECG arrhythmia sequence สำหรับทดสอบ Alarm",
      "สามารถจำลองสัญญาณ Pace Waveform",
      "สามารถกำหนดค่าการจำลองสัญญาณ IBP ได้",
      "สามารถจำลองอัตราการหายใจ",
      "สามารถจำลองอุณหภูมิที่ใช้กับ YSI 400 และ 700",
      "สามารถใช้ทดสอบ Cadiac Output ได้ (ใช้ร่วมกับ MCO-2100 breakout box)",
      "สามารถจำลองสัญญาณ Fetal/Maternal",
    ],
  },
];
var itemsECG = [
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2000 Series",
    link: "?page=ps2000series",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2000.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "จุดเชื่อมต่อแบบกระดุม 6 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ และ PVC Arrhythmia",
      "จำลองสัญญาณ ECG Performance",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2100 Series",
    link: "?page=ps2100series",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2100.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ IBP ได้",
      "จำลองอัตราการหายใจได้ Respiration (Lead LA or LL)",
      "จำลองอุณหภูมิได้เมื่อใช้กับสาย YSI Series 400 หรือ 700",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2200 Series",
    link: "?page=ps2200series",
    hot: true,
    sale: false,
    image: "./assets/images/products/ps2200.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ IBP ได้ (4 Channels)",
      "จำลองอัตราการหายใจได้ Respiration (Lead LA or LL)",
      "จำลองอุณหภูมิได้เมื่อใช้กับสาย YSI Series 400 หรือ 700",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "สามารถทดสอบ Cardiac Output ได้ (อุปกรณ์เสริม)",
      "สามารถจำลอง Fetal/Meternal ได้ (อุปกรณ์เสริม)",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
    ],
  },
];
var itemsPressure = [
  {
    type: "Pressure Tester",
    brand: "BC Biomedical",
    name: "DPM-2001",
    link: "?page=dpm2001",
    hot: true,
    sale: false,
    image: "./assets/images/products/dpm2001.jpg",
    feature: [
      "ช่วงการวัด -13.50 ถึง 100 psi (-698 ถึง 5171 mmHg)",
      "Accuracy 0.1% Full scale",
      "มีหน่วยการวัด PSI, inH2O, cmH2O และ mmHg",
      "การแสดงผลหน้าจอ LCD แบบ 5 digit",
      "ใช้งานกับแบตเตอรี่ 9V แสดงสถานะ 0-100%",
    ],
  },
  {
    type: "Pressure Tester",
    brand: "BC Biomedical",
    name: "DPM-2001PLUS",
    link: "?page=dpm2001plus",
    hot: false,
    sale: false,
    image: "./assets/images/products/dpm2001plus.jpg",
    feature: [
      "ช่วงการวัด -13.50 ถึง 100 psi (-698 ถึง 5171 mmHg)",
      "Accuracy 0.1% Full scale",
      "มีหน่วยการวัด PSI, inH2O, cmH2O และ mmHg",
      "การแสดงผลหน้าจอ LCD แบบ 5 digit",
      "สามารถบันทึกค่า Min/Max ได้",
      "เชื่อมต่อคอมพิวเตอร์ด้วย RS232",
      "ใช้งานกับแบตเตอรี่ 9V แสดงสถานะ 0-100%",
    ],
  },
  {
    type: "Pressure Tester",
    brand: "BC Biomedical",
    name: "DPM-2100",
    link: "?page=dpm2100",
    hot: true,
    sale: false,
    image: "./assets/images/products/dpm2100.jpg",
    feature: [
      "ช่วงการวัด -13.50 ถึง 100 psi (-698 ถึง 5171 mmHg)",
      "Accuracy 0.1% Full scale",
      "มีหน่วยการวัด PSI, inH2O, cmH2O และ mmHg",
      "การแสดงผลหน้าจอ LCD แบบ 5 digit",
      "สามารถบันทึกค่า Min/Max ได้",
      "สามารถจำลองสัญญาณค่าอุณหภูมิ (ใช้กับสาย YSI-700)",
      "เชื่อมต่อคอมพิวเตอร์ด้วย RS232",
      "ใช้งานกับแบตเตอรี่ 9V แสดงสถานะ 0-100%",
    ],
  },
];
var itemsIFP = [
  {
    type: "Infusion Pump Analyzer",
    brand: "BC Biomedical",
    name: "IPA-3400",
    link: "?page=ipa3400",
    hot: true,
    sale: false,
    image: "./assets/images/products/ipa3400.png",
    feature: [
      "ตัวเครื่องขนาดเล็ก ใช้งานง่าย สะดวก รวดเร็ว",
      "มีความแม่นยำสูง",
      "หน้าจอสัมผัสขนาดใหญ่ถึง 7 นิ้ว",
      "สามารถเลือก เพิ่ม/ลด สลับ แชนแนล เองได้ตั้งแต่ 1-4 แชนแนล",
      "มีระบบ Auto Start",
      "มี Auto Sequences ในตัว",
      "บันทึกผลได้ในตัว",
      "รองรับการปฏิบัติตามมาตรฐาน IEC 60601-2-24",
      "ช่วงการวัด 10μL ถึง 1,000 mL/Hr",
      "มี 4 USB Ports และ 4 AUX Ports รองรับการใช้งานกับ Flash Drives, Barcode Scanners, Keyboard และ Mouse",
      "ใช้งานร่วมกับคอมพิวเตอร์ได้",
      "มีหน่วยแรงดัน mmHg, PSI, Bar, kPa",
      "หน่วยความจำในตัวเครื่อง 32GB",
    ],
  },
];
var itemsFlow = [
  {
    type: "Primary Flow Meter",
    brand: "MesaLabs",
    name: "Defender 510 H/M/L",
    link: "?page=defender510",
    hot: true,
    sale: false,
    image: "./assets/images/products/510.png",
    feature: [
      "สามารถวัดอัตราการไหลของแกสได้ตั้งแต่ 5ml/min ถึง 30 LPM (แล้วแต่รุ่น)",
      "ขนาดเล็ก พกพาสะดวก",
      "มีแบตเตอรี่ภายในสามารถชาร์จได้",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "มี Self Test เพื่อตรวจสอบการรั่วไหล",
      "มีระบบการวัดทั้งแบบ Single, Burst และ Continuous",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
      "ใช้งานร่วมกับ Software ได้",
    ],
  },
  {
    type: "Primary Flow Meter",
    brand: "MesaLabs",
    name: "Defender 520 H/M/L",
    link: "?page=defender520",
    hot: false,
    sale: false,
    image: "./assets/images/products/520.jpg",
    feature: [
      "สามารถวัดอัตราการไหลของแกสได้ตั้งแต่ 5ml/min ถึง 30 LPM (แล้วแต่รุ่น)",
      "ขนาดเล็ก พกพาสะดวก",
      "มีแบตเตอรี่ภายในสามารถชาร์จได้",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "มี Self Test เพื่อตรวจสอบการรั่วไหล",
      "มีระบบการวัดทั้งแบบ Single, Burst และ Continuous",
      "สามารถวัด Ambient Temperature และ Pressure ได้",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
      "ใช้งานร่วมกับ Software ได้",
    ],
  },
  {
    type: "Primary Flow Meter",
    brand: "MesaLabs",
    name: "Defender 530+ H/M/L",
    link: "?page=defender530",
    hot: false,
    sale: false,
    image: "./assets/images/products/530.png",
    feature: [
      "ออกแบบมาเพื่อใช้งานด้านอุตสาหกรรมโดยเฉพาะ",
      "สามารถวัดอัตราการไหลของแกสได้ตั้งแต่ 5ml/min ถึง 30 LPM (แล้วแต่รุ่น)",
      "ขนาดเล็ก พกพาสะดวก",
      "มีแบตเตอรี่ภายในสามารถชาร์จได้",
      "ค่า Accuracy ± 1% ของค่าที่อ่านได้",
      "มี Self Test เพื่อตรวจสอบการรั่วไหล",
      "มีระบบการวัดทั้งแบบ Single, Burst และ Continuous",
      "สามารถวัด Ambient Temperature และ Pressure ได้",
      "ใช้งานด้วย Battery ในตัวและสามารถชาร์จได้",
      "ใช้งานร่วมกับ Software ได้",
    ],
  },
];
var itemsUS = [
  {
    type: "Ultrasound Power Meter",
    brand: "Ohmic",
    name: "UPM-DT-10PA",
    link: "?page=upm-dt-10pa",
    hot: true,
    sale: false,
    image: "./assets/images/products/upm.jpg",
    feature: [
      "ผ่านการสอบเทียบ 5 จุด (NIST Traceable)",
      "ความละเอียดสูง: 2 หรือ 20 mW (1.5 หรือ 15 mW ในโหมดกรัม)",
      "ช่วงการวัด: 0-30 watts",
      "ช่วงความถี่ .5 ถึง 10 mhz",
      "วัดพลังงานพัลซิ่งทั้งหมดหรือต่อเนื่อง",
      "ปรับค้่ 0 อัตโนมัติและเสถียรภาพ",
      "หน้าจอดิจิตอลและการเชื่อมต่อ RS-232",
      "มาพร้อมกับกระเป๋าบรรจุ",
    ],
  },
];
var itemsESU = [
  {
    type: "Electrosurgical Analyzer",
    brand: "S.P.L. Elektronik",
    name: "HF-400",
    link: "?page=hf400",
    hot: false,
    sale: false,
    image: "./assets/images/products/hf400.jpg",
    feature: [
      "ควบคุมด้วยเคอร์เซอร์ หรือควบคุมด้วยคอมพิวเตอร์",
      "วัดค่า HF - power",
      "วัดค่า HF - voltage",
      "วัดค่า HF - current",
      "วัดค่า HF - leakage current",
      "ทดสอบ neutral electrode",
      "ทดสอบ load resistances ที่ 10 Ohm, 25 – 6375 Ohm ขั้นละ 25 Ohm",
      "กำหนดความต้านทานล่วงหน้าได้ 6 ค่า",
    ],
  },
];
var itemsPS2000 = [
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2005",
    link: "?page=ps2005",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2005.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "จุดเชื่อมต่อแบบกระดุม 5 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance",
      "Lead test function",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
      "Amplitude accuracy: ± 2%",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2006",
    link: "?page=ps2006",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2006.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "จุดเชื่อมต่อแบบกระดุม 6 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ และ PVC Arrhythmia",
      "จำลองสัญญาณ ECG Performance",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
      "Amplitude accuracy: ± 2%",
      "Frequency accuracy: +/- 0.5% of setting",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2010",
    link: "?page=ps2010",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2010.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance",
      "High level output (1 v p-p)",
      "Lead test function",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
      "Amplitude accuracy: ± 2%",
      "Frequency accuracy: ± 0.5% of setting",
    ],
  },
];
var itemsPS2100 = [
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2105",
    link: "?page=ps2105",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2105.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG ผิดปกติได้ถึง 49 แบบ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ Pacemaker Waveform ได้",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "ช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2110",
    link: "?page=ps2110",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2110.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ IBP ได้",
      "จำลองอัตราการหายใจได้ Respiration (Lead LA or LL)",
      "จำลองอุณหภูมิได้เมื่อใช้กับสาย YSI Series 400 หรือ 700",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
    ],
  },
];
var itemsPS2200 = [
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2210",
    link: "?page=ps2210",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2210.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ IBP ได้ (1 Chanel)",
      "จำลองอัตราการหายใจได้ Respiration (Lead LA or LL)",
      "จำลองอุณหภูมิได้เมื่อใช้กับสาย YSI Series 400 หรือ 700",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "สามารถทดสอบ Cardiac Output ได้ (อุปกรณ์เสริม)",
      "สามารถจำลอง Fetal/Meternal ได้ (อุปกรณ์เสริม)",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2220",
    link: "?page=ps2220",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2220.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ IBP ได้ (2 Channels)",
      "จำลองอัตราการหายใจได้ Respiration (Lead LA or LL)",
      "จำลองอุณหภูมิได้เมื่อใช้กับสาย YSI Series 400 หรือ 700",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "สามารถทดสอบ Cardiac Output ได้ (อุปกรณ์เสริม)",
      "สามารถจำลอง Fetal/Meternal ได้ (อุปกรณ์เสริม)",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
      "ปุ่มกดใช้งานง่าย",
    ],
  },
  {
    type: "Patient Simulator",
    brand: "BC Biomedical",
    name: "PS-2240",
    link: "?page=ps2240",
    hot: false,
    sale: false,
    image: "./assets/images/products/ps2240.jpg",
    feature: [
      "ขนาดเล็กน้ำหนักเบาพกพาสะดวก",
      "หน้าจอแสดงผลแบบ Backlight",
      "จุดเชื่อมต่อแบบ Universal 10 patient lead",
      "จำลองสัญญาณ ECG แบบปกติ",
      "จำลองสัญญาณ ECG Performance ได้",
      "จำลองสัญญาณ IBP ได้ (4 Channels)",
      "จำลองอัตราการหายใจได้ Respiration (Lead LA or LL)",
      "จำลองอุณหภูมิได้เมื่อใช้กับสาย YSI Series 400 หรือ 700",
      "ใช้งานร่วมกับ SpO2 Simulator ได้ (อุปกรณ์เสริม)",
      "สามารถทดสอบ Cardiac Output ได้ (อุปกรณ์เสริม)",
      "สามารถจำลอง Fetal/Meternal ได้ (อุปกรณ์เสริม)",
      "ใช้งานกับแบตเตอรี่ 9V พร้อมไฟแสดงสถานะ",
    ],
  },
];
